//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api_futebass_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELENCO
    {
        public int ElencoId { get; set; }
        public int JogadorId { get; set; }
        public int PartidaId { get; set; }
    
        public virtual JOGADOR JOGADOR { get; set; }
        public virtual PARTIDA PARTIDA { get; set; }
    }
}
