CREATE TABLE JOGADOR(
JogadorId int not null identity(1,1),
Nome VARCHAR(500) NOT NULL,
Cidade VARCHAR(500) NOT NULL,
Foto VARCHAR(1000) NOT NULL,
Nivel VARCHAR(500) NOT NULL,
IdSocial TEXT NOT NULL

PRIMARY KEY (JogadorId)
)

CREATE TABLE PARTIDA(
PartidaId int not null identity(1,1),
JogadorId INT NOT NULL,
DataHora DATETIME NOT NULL,
Observacao VARCHAR(1000) NOT NULL,
Preco INT NOT NULL,
Tipo VARCHAR(500) NOT NULL,
Local VARCHAR(100) NOT NULL

PRIMARY KEY(PartidaId)
FOREIGN KEY (JogadorId) REFERENCES JOGADOR(JogadorId),
)

CREATE TABLE ELENCO(
ElencoId INT NOT NULL IDENTITY(1,1),
JogadorId INT NOT NULL,
PartidaId INT NOT NULL,

PRIMARY KEY (ElencoId),
FOREIGN KEY (JogadorId) REFERENCES JOGADOR(JogadorId),
FOREIGN KEY (PartidaId) REFERENCES PARTIDA(PartidaId)
)